config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :boards do
    get :password
    post :password
    resources :items do
      resources :comments
      resources :votes
    end
  end
  resources :users  

  root 'welcome#index'
  
  
  

end

app/models/comment.rb
require 'user_namable'
require 'sluggable'

class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :item, counter_cache: true, :touch => true

  scope :recent, -> { order(id: :desc) }

  include UserNamable
  before_save :set_user

  extend FriendlyId
  friendly_id :slug, use: :slugged

  include Sluggable
  after_create :generate_slug

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_board
  before_action :set_item
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = @item.comments.recent
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @item.comments.new(user_name: cookies.signed[:last_user_name])
  end

  # GET /comments/1/edit
  def edit
    @comment.user_name = @comment.user.try(:name)
  end

  # POST /comments
  # POST /comments.json
  def create
    cookies.signed[:last_user_name] = comment_params[:user_name]

    @comment = @item.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @board, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @board, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @board, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.friendly.find(params[:board_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = @board.items.friendly.find(params[:item_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = @item.comments.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment, :user_name)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.comment
  %p= comment.comment 
  .float-right.small
    = link_to 'Edit', edit_board_item_comment_path(@board, @item, comment)
    &nbsp; &nbsp; | &nbsp; &nbsp;
    = link_to 'Delete', board_item_comment_path(@board, @item, comment), method: :delete, data: {confirm: 'Are you sure you want to delete this comment?'}
  .small.left
    = comment.user.name unless comment.user.blank?
    &nbsp; &nbsp; | &nbsp; &nbsp; 
    = time_ago_in_words(comment.created_at).capitalize
    
  

app/views/comments/_form.html.haml
.row.buffer.thrice 
  .col-sm-12.center
    = form_for([@board, @item, @comment]) do |f|
      - if @comment.errors.any?
        #error_explanation
          %h2
            = pluralize(@comment.errors.count, "error")
            prohibited this comment from being saved:
          %ul
            - @comment.errors.full_messages.each do |message|
              %li= message

      .field
        = f.label :comment
        .wide-text
          = f.text_area :comment, autofocus: true
          
      .field.buffer.twice
        = f.label :user_name, 'Your Name'
        .wide-text
          = f.text_field :user_name, class: 'autocomplete', data: {autocomplete: @board.names}
          
      .actions.buffer.thrice
        = f.submit 'Save', class: 'btn btn-default'
        &nbsp; &nbsp;
        = link_to('Cancel', @board, class: 'btn btn-default')

app/views/comments/_inline_form.html.haml
.row.inline-comment-form.slide-hide
  .col-sm-12.center.buffer.twice
    = form_for([@board, item, vote]) do |f|
      .field.buffer
        %p Vote Up This Item
        = f.text_field :user_name, class: 'autocomplete', placeholder: 'Your Name', data: {autocomplete: @board.names}, autofocus: true
        = f.submit 'Save', class: "btn btn-default #{item.column_name.downcase}-grad"
        %a.slide-hide-hide.btn.btn-default Cancel

app/views/comments/edit.html.haml
%h3.text-center Edit Comment

= render 'form'

app/views/comments/index.html.haml
.row
  .col-sm-12.center
    %h3 Comments for:
    %p.buffer= @item.title
  

.row.buffer
  .col-sm-12.center
    = link_to('Add A Comment', new_board_item_comment_path(@board, @item), class: 'btn btn-default')

.row.buffer.twice
  .col-sm-12.col-md-offset-4.col-md-4
    - if @comments.empty?
      %p.center.buffer.thrice There are no comments for this item yet.
    
    = render @comments
      

app/views/comments/new.html.haml
.row
  .col-sm-12.center
    %h3 Add A Comment
    %p= @item.title
    
.row
  .col-sm-12.center
    = render 'form'
    

app/views/comments/show.html.haml
%p#notice= notice
%p
  %strong Comment:
  = @comment.comment
%p
  %strong Item:
  = @comment.item_id
%p
  %strong User:
  = @comment.user_id
= link_to 'Edit', edit_board_item_comment_path(@board, @item, @comment)
|
\#{link_to 'Back', @board}