config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :boards do
    get :password
    post :password
    resources :items do
      resources :comments
      resources :votes
    end
  end
  resources :users  

  root 'welcome#index'
  
  
  

end

app/models/group.rb
class Group < ActiveRecord::Base
  
  has_many :boards
  belongs_to :parent_group, class_name: 'Group'
  has_many :children, class_name: 'Group', foreign_key: 'parent_group_id'

  extend FriendlyId  
  friendly_id :title, use: :slugged

  attr_accessor :child_group_id
  after_create :associate_child
  
  private
  
  def associate_child
    return unless child_group_id
    child_group = Group.find_by_id(child_group_id)
    child_group.update_attributes(parent_group_id: id) unless child_group.nil?
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @children = @group.children
    @boards = @group.boards
  end

  # GET /groups/new
  def new
    @group = Group.new(child_group_id: params[:child_group_id], parent_group_id: params[:parent_group_id])
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    if !verify_recaptcha(model: @group)
      render :new
      return
    end

    render text: 'Go Away!' and return if @group.description =~ /http/

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:title, :description, :parent_group_id, :child_group_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= form_for(@group) do |f|
  - if @group.errors.any?
    #error_explanation
      %h2
        = pluralize(@group.errors.count, "error")
        prohibited this group from being saved:
      %ul
        - @group.errors.full_messages.each do |message|
          %li= message

  .field.buffer.thrice
    = f.label :title
    .wide-text
      = f.text_field :title

  .field.buffer.thrice
    = f.label :description
    .wide-text
      = f.text_area :description

  .field.buffer.thrice
    = recaptcha_tags

  .actions.buffer.thrice
    = f.hidden_field :child_group_id
    = f.hidden_field :parent_group_id
    = f.submit 'Save', class: 'btn btn-default'
    = link_to 'Cancel', root_path, class: 'btn btn-default'

app/views/groups/edit.html.haml
%h1 Editing Group
= render 'form'
= link_to 'Show', @group
|
\#{link_to 'Back', groups_path}

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Parent group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.title %></td>
        <td><%= group.description %></td>
        <td><%= group.parent_group_id %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.haml
.row
  .col-sm-12.center
    %h3 New Project or Organization or Group

.row
  .col-sm-12.center
    = render 'form'

app/views/groups/show.html.haml
#notice.center= notice

.row
  .col-sm-12.center
    %h3= @group.title
    - if @group.description.present?
      %p= @group.description

.row.buffer.twice

  .col-sm-12.col-md-6
    %h5 Retrospective Boards
    - if @boards.empty?
      %p
        = @group.title
        does not have any retrospective boards associated with it.
    
    %p= link_to 'Create A New Retrospective Board', new_board_path(group_id: @group.id), class: 'btn btn-primary'
    
    - @boards.each do |board|
      %p= link_to board.name, board_path(board, p: board.password)


  .col-sm-12.col-md-6
    %h5 Parent Organization / Project
    - if @group.parent_group
      %p= link_to @group.parent_group.title, @group.parent_group
    - else
      %p
        = @group.title
        does not have a parent organization / group.

    %p= link_to 'Create A Parent Group', new_group_path(child_group_id: @group.id), class: 'btn btn-primary'
    
    %br
    %br 
    
    %h5 Sub Projects / Groups
    - if @children.empty?
      %p
        = @group.title
        does not have any associated sub groups.
        
    - @children.each do |group|
      %p= link_to group.title, group
      
    %p= link_to 'Create Sub Group', new_group_path(parent_group_id: @group.id), class: 'btn btn-primary'