config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :boards do
    get :password
    post :password
    resources :items do
      resources :comments
      resources :votes
    end
  end
  resources :users  

  root 'welcome#index'
  
  
  

end

app/models/item.rb
require 'user_namable'
require 'sluggable'

class Item < ActiveRecord::Base
  belongs_to :board, :touch => true
  belongs_to :user
  has_many :comments
  has_many :votes
  
  scope :updated_after, -> (time) { where("updated_at > ?", time) }
  scope :for_column, -> (column_name) { where("column_name = ?", column_name.downcase) }  
  scope :voted, -> { order(votes_count: :desc, comments_count: :desc, id: :desc)} 
  scope :recent, -> { order(id: :desc) } 
  
  validates_presence_of :title

  include UserNamable  
  before_create :set_user

  extend FriendlyId  
  friendly_id :slug, use: :slugged
  
  include Sluggable  
  after_create :generate_slug
  
  attr_accessor :comment
  after_create :create_comment
  
  after_create :create_vote
  
  before_save :downcase_column_name
  
  def votes_list
    votes.map(&:user).compact.map(&:name).compact.join(', ')
  end

  private
  
  def create_comment
    return unless comment.present?
    self.comments.create(comment: comment, user: user)
  end
  
  def create_vote
    self.votes.create(user: user)
  end
  
  def downcase_column_name
    self.column_name = column_name.downcase
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_board
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items/1
  # GET /items/1.json
  def show
    @comments = @item.comments.recent
    @votes = @item.votes.recent
  end

  # GET /items/new
  def new
    @item = @board.items.new(column_name: params[:column_name], user_name: cookies.signed[:last_user_name])
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    cookies.signed[:last_user_name] = item_params[:user_name]
    
    @item = @board.items.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @board, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @board, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to @board, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.friendly.find(params[:board_id])
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = @board.items.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :column_name, :user_name, :comment)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_comments_info.html.haml
%h7
  - if item.comments.length <= 0
    = link_to('Add Comment', new_board_item_comment_path(@board, item))
  - else                           
    = link_to("<span class='comment-count'>#{pluralize(item.comments.length, 'Comment')}</span>".html_safe, board_item_path(@board, item), title: item.comments.map(&:user).compact.map(&:name), alt: item.comments.map(&:user).compact.map(&:name))

app/views/items/_form.html.haml
.row.buffer.thrice 
  .col-sm-12.center
    = form_for([@board, @item]) do |f|
      - if @item.errors.any?
        #error_explanation
          %h2
            = pluralize(@item.errors.count, "error")
            prohibited this item from being saved:
          %ul
            - @item.errors.full_messages.each do |message|
              %li= message
      
      .field
        = f.label :title
        .wide-text
          = f.text_field :title, autofocus: true
          = f.hidden_field :column_name
      
      - if @item.new_record?
        .field.buffer.thrice
          = f.label :comment
          .wide-text
            = f.text_area :comment
      
      .field.buffer.thrice
        = f.label :user_name, 'Added By (Your Name)'
        .wide-text
          = f.text_field :user_name, class: 'autocomplete', data: {autocomplete: @board.names}
      
      .actions.buffer.thrice
        = f.submit 'Save', class: 'btn btn-default'
        &nbsp; &nbsp;
        = link_to 'Cancel', @board, class: 'btn btn-default'

app/views/items/_inline_form.html.haml
.row.inline-item-form.slide-hide
  .col-sm-12.center.buffer.twice
    = form_for([@board, item]) do |f|
      .field
        .wide-percentage-text
          = f.text_field :title, placeholder: 'Title', autofocus: true
          = f.hidden_field :column_name
      
      - if item.new_record?
        .field.buffer
          .wide-percentage-text
            = f.text_area :comment, placeholder: 'Your Comments'
      
      .field.buffer
        = f.text_field :user_name, class: 'autocomplete', placeholder: 'Your Name', data: {autocomplete: @board.names}
        = f.submit 'Save', class: "btn btn-default #{item.column_name.downcase}-grad"
        %a.slide-hide-hide.btn.btn-default Cancel

app/views/items/_item.html.haml
.row.item{id: "item-#{item.id}"}
  .col-sm-12.buffer.twice   
    .inner{class: "#{item.column_name}-grad"}
      %h6.center= link_to(item.title, board_item_path(@board, item), class: 'title-info')

      .row.center
        .col-sm-12
          .vote-info
            = render partial: 'items/votes_info', locals: {item: item}

      - unless item.comments.empty?
        .row.buffer
          .col-sm-12
            %p.small= truncate(item.comments.first.comment, length: 200)

      .row.small.center
        .col-sm-6
          %h7= "By #{item.user.blank? ? 'Anon' : item.user.name}"
        .col-sm-6.comment-info
          = render partial: 'items/comments_info', locals: {item: item}

      .row.small.center.buffer
        .col-sm-12                 
          = link_to('Edit', edit_board_item_path(@board, item))                    
          &nbsp;
          |
          &nbsp;
          = link_to('Delete', board_item_path(@board, item), method: :delete, data: {confirm: 'Are you sure you want to delete this item?'})
    
      = render partial: 'votes/inline_form', locals: {item: item, vote: item.votes.new(user_name: @last_user_name)}
        
        

app/views/items/_votes_info.html.haml
%h7
  %a.slidebutton{data: {slideclosest: '.item', slidefind: '.inline-vote-form'}} Vote Up
  / = link_to('Vote', new_board_item_vote_path(@board, item))
  &nbsp;
  = link_to("( <span class='vote-count small'>#{pluralize(item.votes.map(&:id).compact.length, 'Up Vote')}</span> )".html_safe, board_item_path(@board, item), title: item.votes_list, alt: item.votes_list)

app/views/items/edit.html.haml
%h3.text-center Edit Item
= render 'form'

app/views/items/new.html.haml
.row
  .col-sm-12.center
    %h4
      Add A
      = @item.column_name.capitalize
      Item
      To The
      = @board.name
      Board
    %br
    %h5= @board["#{@item.column_name.downcase}_column_description"]
      
.row
  .col-sm-12.center
    = render 'form'

app/views/items/show.html.haml
#notice.center= notice

.row
  .col-sm-12.center
    %h2= link_to(@board.name, @board)

.row
  .col-sm-12.center
    %h3= @item.title
    %p 
      From The
      = @item.column_name.capitalize
      Column 
    %p
      - unless @item.user.blank?
        Added by
        = @item.user.name
      = time_ago_in_words(@item.created_at)
      ago
    %p
      = link_to 'Edit', edit_board_item_path(@board, @item)
      &nbsp; &nbsp; | &nbsp; &nbsp;
      = link_to 'Delete', board_item_path(@board, @item), method: :delete, data: {confirm: 'Are you sure you want to delete this item?'}
      
.row.buffer
  .col-sm-12.col-md-6.center 
    .row.buffer
      .col-sm-12.center
        = link_to('Add A Comment', new_board_item_comment_path(@board, @item), class: 'btn btn-default')

    .row
      .col-sm-12.col-md-offset-1.col-md-10
        - if @comments.empty?
          %p.center.buffer.thrice There are no comments for this item yet.

        = render @comments
        

  .col-sm-12.col-md-6.center    
    .row.buffer.col-sm-12
      = link_to('Vote Up This Item', new_board_item_vote_path(@board, @item), class: 'btn btn-default')

    .row.buffer.twice
      .col-sm-12.col-md-offset-1.col-md-10
        - if @votes.empty?
          %p.center.buffer.thrice There are no up votes for this item yet.
    
        = render @votes
          